### ISSUE TITLE
Doubts about the simulation results of the MySimpleHandshakeMac protocol

### ISSUE THREAD

**Issue by Lucifish21** [org-arl/unet-contrib#20]
The relevant simulation results are shown in the figure below.
The simulation results of the MysimplestMac protocol are reasonable, but the results of the MySimpleHandshakeMac protocol are not understood. 
Why is the network load not increasing and the throughput is low?
In theory, the throughput based on the handshake mechanism MAC protocol should be an incremental process.
<img width="327" alt="MySimpleHandshakeMac" src="https://user-images.githubusercontent.com/38817121/57198362-569d9b80-6fa4-11e9-99b6-f148a8c6e76b.png">
<img width="330" alt="MySimplestMac" src="https://user-images.githubusercontent.com/38817121/57198363-58fff580-6fa4-11e9-84fa-24b4af30c8c1.png">

**Comment by mchitre** [comment]
The throughput of `MySimpleHandshakeMac` is low because the protocol is simple (for demonstration of how to implement handshakes), and not optimized for performance.

The `MySimpleHandshakeMac` queues medium access requests. Data is only technically offered to the PHY once the request is granted. The table shows PHY offered load and hence you don't see it increased. If you measure the load (requests) offered to MAC instead, you'll see an increasing offered load.

The measurement at PHY/MAC in no difference for ALOHA or `MySimplestMac` because they grant requests immediately, and so the data is immediately offered to PHY.
